### PR TITLE
Added second player and its' movement with WASD + attack

### PR DESCRIPTION
**Pull request by RaduApr**

### CODE REVIEW

**Comment by kicsyromy** [comment]
Is this two PRs in one?

**Comment by RaduApr** [comment]
I was intending to do another one, but if you consider that it is enough for both PRs it is fine with me. =) If not, I can try and make one more.

**Comment by kicsyromy** [comment]
Pleas do, because this is not enough for two grades.

**Comment by RaduApr** [comment]
Ok

**Pull request closed without merging**
